version: '3'

services:
  zookeeper1:
    image: zookeeper:latest
    restart: always
    hostname: zookeeper1
    container_name: zookeeper1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 10
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

  zookeeper2:
    image: zookeeper:latest
    restart: always
    hostname: zookeeper
    container_name: zookeeper2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 20
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

  zookeeper3:
    image: zookeeper:latest
    restart: always
    hostname: zookeeper
    container_name: zookeeper3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 30
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
